---
name: Testing

# yamllint disable-line rule:truthy
on:
  pull_request:

jobs:
  jest:
    name: Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 22]
    steps:
      - name: â¤µï¸ Check out code from GitHub
        uses: actions/checkout@v4.1.7
      - name: ğŸ— Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ matrix.node-version }}
      - name: ğŸ— Install dependencies
        run: npm ci
      - name: ğŸš€ Run tests
        run: npm test
      - name: â¬†ï¸ Upload coverage artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: coverage-${{ matrix.node-version }}
          path: coverage
          retention-days: 1

  coverage:
    runs-on: ubuntu-latest
    needs: jest
    steps:
      - name: â¤µï¸ Check out code from GitHub
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
      - name: â¬‡ï¸ Download coverage data
        uses: actions/download-artifact@v4.1.7
      - name: ğŸ§ª Display structure of job
        run: ls -R
      - name: ğŸ“¦ Merge coverage reports
        run: npx nyc merge coverage-*/coverage-final.json
      - name: ğŸ§ª Display structure of job
        run: ls -R
